name: Contrat_Sous_Location

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 1 * *'

jobs:
  Contrat_Sous_Location:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install French locale
      run: |
        sudo apt-get update
        sudo apt-get install -y language-pack-fr
        sudo locale-gen fr_FR.UTF-8
        sudo update-locale LANG=fr_FR.UTF-8

    - name: Set LC_ALL to fr_FR.UTF-8
      run: echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Inject environment variables from GitHub Secrets
      run: |
        echo "ADRESSE_PROPRIO=${{ secrets.ADRESSE_PROPRIO }}" >> $GITHUB_ENV
        echo "ADRESSE_LOCATION=${{ secrets.ADRESSE_LOCATION }}" >> $GITHUB_ENV
        echo "IBAN=${{ secrets.IBAN }}" >> $GITHUB_ENV
        echo "BIC=${{ secrets.BIC }}" >> $GITHUB_ENV
        echo "NOM_PROPRIO=${{ secrets.NOM_PROPRIO }}" >> $GITHUB_ENV
        echo "LOCATAIRE=${{ vars.LOCATAIRE }}" >> $GITHUB_ENV
        echo "DESTINATAIRE=${{ secrets.DESTINATAIRE }}" >> $GITHUB_ENV
        echo "DESTINATAIRE_CCI=${{ secrets.DESTINATAIRE_CCI }}" >> $GITHUB_ENV
        echo "EXPEDITEUR=${{ secrets.EXPEDITEUR }}" >> $GITHUB_ENV
        echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
        echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
        echo "GOOGLE_SHEET_URL=${{ secrets.GOOGLE_SHEET_URL }}" >> $GITHUB_ENV
        echo "DB_PATH=${{ secrets.DB_PATH }}" >> $GITHUB_ENV

    - name: Run 1_contrat_sous_location.py
      run: python 1_contrat_sous_location.py

    - name: Run mail_contrat_sous_location.py
      run: python mail_contrat_sous_location.py
