- name: Inject environment variables from GitHub Secrets
      run: |
        echo "ADRESSE_PROPRIO=${{ secrets.ADRESSE_PROPRIO }}" >> $GITHUB_ENV
        echo "ADRESSE_LOCATION=${{ secrets.ADRESSE_LOCATION }}" >> $GITHUB_ENV
        echo "IBAN=${{ secrets.IBAN }}" >> $GITHUB_ENV
        echo "BIC=${{ secrets.BIC }}" >> $GITHUB_ENV
        echo "NOM_PROPRIO=${{ secrets.NOM_PROPRIO }}" >> $GITHUB_ENV
        echo "LOCATAIRE=${{ vars.LOCATAIRE }}" >> $GITHUB_ENV
        echo "DESTINATAIRE=${{ secrets.DESTINATAIRE }}" >> $GITHUB_ENV
        echo "DESTINATAIRE_CCI=${{ secrets.DESTINATAIRE_CCI }}" >> $GITHUB_ENV
        echo "EXPEDITEUR=${{ secrets.EXPEDITEUR }}" >> $GITHUB_ENV
        echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
        echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
        echo "GOOGLE_SHEET_URL=${{ secrets.GOOGLE_SHEET_URL }}" >> $GITHUB_ENV
        echo "DB_PATH=${{ secrets.DB_PATH }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> $GITHUB_ENV
